# Generated by Django 5.0 on 2023-12-31 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cportal', '0004_alter_company_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('PVT', 'Private Limited'), ('LTD', 'Public Limited'), ('SLP', 'Sole Proprietorship'), ('None', 'Unknown')], default='Unknown', max_length=4),
        ),
        migrations.AddField(
            model_name='company',
            name='zip',
            field=models.CharField(default=None, max_length=6, null=True),
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('din', models.CharField(default=None, max_length=30, null=True)),
                ('status', models.CharField(choices=[('ACT', 'ACTIVE'), ('DRM', 'DORMANT'), ('INAC', 'INACTIVE'), ('DRFT', 'DRAFT')], default='DRAFT', max_length=15)),
                ('address', models.CharField(default=None, max_length=40, null=True)),
                ('zip', models.CharField(default=None, max_length=6, null=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.state')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.country')),
            ],
        ),
    ]
