# Generated by Django 5.0 on 2023-12-31 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cportal', '0005_company_address_company_type_company_zip_director'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gstin',
            field=models.CharField(default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='pan',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='tan',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='director',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.company'),
        ),
        migrations.AddField(
            model_name='director',
            name='pan',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
