# Generated by Django 5.0 on 2023-12-31 04:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cportal', '0007_company_email_company_phone_director_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='city',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='director',
            old_name='city',
            new_name='state',
        ),
    ]
