# Generated by Django 5.0 on 2023-12-31 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cportal', '0008_rename_city_company_state_rename_city_director_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='tan',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
