# Generated by Django 5.0 on 2023-12-31 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cportal', '0009_alter_company_gstin_alter_company_pan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='din',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='pan',
            field=models.CharField(blank=True, default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('INAC', 'INACTIVE'), ('DRFT', 'DRAFT')], default='DRAFT', max_length=15),
        ),
        migrations.AlterField(
            model_name='director',
            name='zip',
            field=models.CharField(blank=True, default=None, max_length=6, null=True),
        ),
    ]
