# Generated by Django 5.0 on 2023-12-31 21:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cportal', '0011_remove_director_company_companydirector_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AlterModelOptions(
            name='companydirector',
            options={'verbose_name': 'Associated with'},
        ),
        migrations.AlterModelOptions(
            name='director',
            options={'verbose_name': 'Director', 'verbose_name_plural': 'Directors'},
        ),
        migrations.AlterField(
            model_name='company',
            name='address',
            field=models.CharField(default=None, max_length=40, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='company',
            name='cin',
            field=models.CharField(default=None, max_length=30, null=True, verbose_name='CIN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Company Email'),
        ),
        migrations.AlterField(
            model_name='company',
            name='gstin',
            field=models.CharField(blank=True, default=None, max_length=20, null=True, verbose_name='GSTIN'),
        ),
        migrations.AlterField(
            model_name='company',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='company',
            name='pan',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='PAN #'),
        ),
        migrations.AlterField(
            model_name='company',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('DRM', 'DORMANT'), ('INAC', 'INACTIVE'), ('DRFT', 'DRAFT')], default='DRAFT', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tan',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='TAN #'),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.CharField(choices=[('PVT', 'Private Limited'), ('LTD', 'Public Limited'), ('SLP', 'Sole Proprietorship'), ('None', 'Unknown')], default='Unknown', max_length=4, verbose_name='Company Type'),
        ),
        migrations.AlterField(
            model_name='company',
            name='zip',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='director',
            name='address',
            field=models.CharField(blank=True, default=None, max_length=40, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='director',
            name='company',
            field=models.ManyToManyField(through='cportal.CompanyDirector', to='cportal.company', verbose_name='Linked Companies'),
        ),
        migrations.AlterField(
            model_name='director',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='director',
            name='din',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='DIN #'),
        ),
        migrations.AlterField(
            model_name='director',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='director',
            name='pan',
            field=models.CharField(blank=True, default=None, max_length=10, null=True, verbose_name='PAN #'),
        ),
        migrations.AlterField(
            model_name='director',
            name='state',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.state', verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='director',
            name='status',
            field=models.CharField(choices=[('ACT', 'ACTIVE'), ('INAC', 'INACTIVE'), ('DRFT', 'DRAFT')], default='DRAFT', max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='director',
            name='zip',
            field=models.CharField(blank=True, default=None, max_length=6, null=True, verbose_name='Zip Code'),
        ),
    ]
