# Generated by Django 5.0 on 2023-12-31 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cportal', '0012_alter_company_options_alter_companydirector_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='account',
        ),
        migrations.RemoveField(
            model_name='companydirector',
            name='owner',
        ),
        migrations.AddField(
            model_name='companydirector',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.company', verbose_name='Company'),
        ),
        migrations.AddField(
            model_name='companydirector',
            name='director',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.director', verbose_name='Director'),
        ),
    ]
