# Generated by Django 5.0 on 2024-01-01 03:04

import cportal.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cportal', '0014_alter_companydirector_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200, verbose_name='Order Type')),
                ('description', models.TextField(help_text='Enter a brief description of the Order Type', verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(choices=cportal.models.OrderType.get_currencies, max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('COMPLETED', 'COMPLETED'), ('RENEWED', 'RENEWED'), ('CANCELLED', 'CANCELLED'), ('RECEIVED', 'RECEIVED')], default='RECEIVED', max_length=15, verbose_name='Status')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.company', verbose_name='Company')),
                ('type', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cportal.ordertype', verbose_name='Order Type')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
